### ISSUE TITLE
vipDS9 missing?

### ISSUE THREAD

**Issue by henry-ngo** [vortex-exoplanet/VIP#109]
I am updating NIRC2_Preprocessing and our pipeline. I found through the commit history that the vipDS9 module moved from vip.fits to vip.exlib. But the most current version of exlib doesn't have vipDS9 at all?

Was that intentional? Will VIP no longer use this external library? Or, did it just go missing? Here's the last version where I could see the necessary files: https://github.com/vortex-exoplanet/VIP/tree/ceb7a1f738d329c209f005c261d6da60edce01d7/vip_hci/exlib

**Comment by carlgogo** [comment]
Yes it was intentional. ``vipDS9`` was a class I wrote to allow a smooth connection to DS9 from a session with VIP. The actual Python-DS9 bridge (through XPA) was supported on an old (and unmaintained) package RO.DS9 that I copied in ``vip_hci.exlib``. While making VIP compatible with Python 3, I noticed that porting RO.DS9 would be a non-trivial proces. I decided to drop it as anyway it is not the main functionality provided by VIP. Also, there several are other projects out there providing such Python-DS9 connection: pyds9 (from the SAO DS9 team) and imexam (astropy affiliated package). I suggest to take a look at those packages. Maybe in the near future we could refactor the ``vipDS9`` class to use pyds9 or imexam.

**Comment by henry-ngo** [comment]
Okay, good to know! We don't actually use vipDS9 anymore in our main reduction pipeline. But the NIRC2_Preprocessing package still imports it and I wasn't sure if others who use NIRC2_Preprocessing might rely on it. 

With this info, I'll also remove the calls to vipDS9 in NIRC2_Preprocessing.
