### ISSUE TITLE
fit_2dgaussian: problem with outputs

### ISSUE THREAD

**Issue by brunellacarlomagno** [vortex-exoplanet/VIP#130]
Hi Carlos,
I am having an issue with fit_2dgaussian, for the full_output option. The results are not numbers (like in the no-full_output case) but strings: for example, ycen='amplitude' and theta='theta', so that theta[3]='t'. 
I update python to python 3 and vip last week, can this be the problem?
Thanks
Have a nice day
Brunella

**Comment by carlgogo** [comment]
Hi Brunella, maybe this is due to the fact that vip.var.fit_2dgaussian returns a Pandas dataframe when you set ``full_output`` to True. For example, if you run:
```python
 fit = vip.var.fit_2dgaussian(psf, True, full_output=True)
```
Then just print the variable fit and you'll see a nice table (or just call it in the jupyter notebook and it will look nicer).  If you want get one of the columns, let's say theta then:
```python
 fit['theta']
```
I hope it helps. Cheers.
