### ISSUE TITLE
vipDS9

### ISSUE THREAD

**Issue by maddalenareggiani** [vortex-exoplanet/VIP#20]
Hi Carlos, 

since yesterday I am having problems displaying fits files with ds9 through VIP.
I have seen it has changed and I tried both
the old vip.fits.display_array_ds9() and
vip.fits.vipds9.vipDS9.display()
but it did not work.
I don't know if this is part of all the broken things I had yesterday, or if I am not using it correctly.
Is it working fine for you?

Thanks,
Maddalena

**Comment by carlgogo** [comment]
Hi Maddalena,

The *vipDS9* class should be used like I show in the tutorial, first you instantiate the ds9 window object, then you use the method *display*:
>>> ds9 = vip.fits.vipDS9()
>>> ds9.display(numpy_array)

You can create several ds9 windows, if you need, and operate them separately (this vipDS9 class has several methods besides displaying an array). 

I left the old function *display_array_ds9* for backward compatibility but it has a small bug indeed, thanks for noticing it. I'll correct that in a minute, but I recommend to use the new class instead of the old function.

Cheers,
Carlos
