### ISSUE TITLE
default frame center for even images

### ISSUE THREAD

**Issue by jmilou** [vortex-exoplanet/VIP#255]
Hi Carlos, 

I noticed that the frame center assumed by VIP is not what most people use as a convention, and this can be dangerous for accurate astrometry. 

If the frame is even (which is what most people use, since the native format of images is even and since for fft for instance powers of 2 are faster), VIP always assume the center to be at the corner between 4 pixels (which is what the function frame_center returns). 
However data cubes are typically (for instance from the SPHERE data center) 1024 by 1024 and centred in the pixel of coordinates [512,512] (in python 0-based indexing style). 

This is possible to handle this issue in the fake disk utilities that I am currently developing as part of vip_hci.metrics.fakedisk (I had added the argument cxy  allowing users to specify a center of [512,512] different from the default value of VIP of [511.5,511.5]. 
However for most star subtraction algorithms included in VIP (for instance vip_hci.pca.pca), this is not possible to specify the frame center, and it assumes to the star is at the position returned by the function frame_center. 
Would you like to add the center as a user parameter?
If it involves a lot of changes, we should get a clear warning when working with even images.  

Cheers
Julien

**Comment by carlgogo** [comment]
Hi @jmilou, this was discussed and fixed in #114 . Please check that out. VIP now correctly handles even and odd-sized images sequences.

**Comment by jmilou** [comment]
Thanks @carlgogo for pointing me to this thread #114 . I had seen it actually, and agree this works fine if for even images, one adopt the frame center definition of Skimage (center = size/2. - 0.5). 
What should be made clear I think is that using even frames with the star center in the middle of a pixel is wrong, just as a warning, because as I say most users (at least from the SPHERE consortium from what I reckon) actually use this convention. 
This is why I was thinking a warning could be useful

**Comment by carlgogo** [comment]
Hi guys, I think we might be talking about different things. 

It seems we agree that VIP can handle frames with even or odd sizes and find the center, correctly apply rotations, inject companions, etc. In the attached image below, this would be `psf1` and `psf2`. This is under the assumption that the star is correctly centered in the array. If that is not the case (`psf3`), the idea is that the user should apply the frame recentering procedures in VIP to take care of this. 

![image](https://user-images.githubusercontent.com/12588564/42950142-a77bb9a8-8b73-11e8-96a8-8def0ad5a342.png)

@jmilou I agree with you that having even frames and assuming the star center in the middle of a pixel is wrong (the case of `psf3`) but I don't see why we should output a warning here. If we follow that road, then we must include dozens of warnings at every step of an image processing pipeline. I have heard the same comment a couple of times already, and still my impression is that a general purpose package, such as VIP, should assume some prior domain knowledge from the side of the user. Of course, this is open to debate so let me know your thoughts.

**Comment by oabsil** [comment]
Hi guys, here are my two cents:

I don't think there is anything fundamentally wrong with the star not being centered at size/2 - 0.5 in even images. Actually, in raw images the star will certainly not be centered there, and it's up to each instrument team to define its own conventions for the pre-processing steps. As an instrument-agnostic package, VIP should ideally be able to handle any centering convention. Yet, I understand that making the whole VIP internal machinery compliant with random centering convention is not convenient, nor desirable. Therefore, I would suggest to make it clear in the VIP documentation and routine/function description that VIP will assume the star to be centered at size/2 - 0.5. It will then be up to the user to make sure that their images comply with this convention. (Pointing towards the frame-shifting functionality of VIP at relevant places of the documentation would be useful in that context.)

Now, if it turns out that *all* HCI instruments use even pixel numbers and centering in the middle of one pixel, it might be useful to consider making VIP compliant with this convention, either by systematically checking for this and shifting the images by half a pixel (easier), or by modifying the internal VIP conventions (probably not desirable, especially if VIP complies with Skimage conventions).

**Comment by carlgogo** [comment]
@oabsil thank you for your input. I agree that *only* if the star not being centered at size/2 - 0.5 is the norm VIP should assume a specific convention. In all fairness, it's true there was a convention in VIP asking odd sized frames and PSFs but we've worked to make every step compatible with both odd and even size cases.

I see 4 solutions here (in incremental order of complexity):
* Doing nothing and assuming the user has its star centered at size/2 - 0.5.
* Include a warning in the documentation saying that the star must be centered at the center of the array. The case of even-sized frames with the star centered in the middle of a pixel can be fixed easily, just dropping a row and a column (takes a single line of code with Numpy).
* As @jmilou suggested we could expose the `cxy` argument of the `cube_derotate` function in *every* (!!!) function in VIP that does some ADI de-rotation. 
* Conducting a survey among all HCI instruments and find if there is a convention VIP must follow.
