### ISSUE TITLE
VIP having trouble identifying companions; parallactic angle issue?

### ISSUE THREAD

**Issue by kjbrooks** [vortex-exoplanet/VIP#410]
I am using VIP in order to reduce data from NACO and I have been having some issues getting the expected results. I have been working through your notebook `01_adi_pre-postproc_fluxpos_ccs` in the `VIP-extras` repository and updating it with and for my data. We have a pipeline that does ADI, but we hope to use VIP so we can use the functionality to combine ADI and RDI. We have been using our pipeline outputs as a comparison with what VIP gives, and so far the results are very different. Essentially, I have been having a hard time getting VIP to identify companions for my data, even in the case where companions are visible in the input data. I am worried that the issue here is with how we are giving parallactic angles to VIP and how that relates to the `derot` parameter. Or if there is an issue with how VIP expects the parallactic angles relative to the Northern/Southern Hemisphere. I have tried to use VIP's function for finding parallactic angles, but unfortunately, the results I obtained also did not provide results that were that much closer to what we expect. I am wondering if there is a special relationship between the parallactic angles and the `derot` variable that might help fix this issue? Any suggestions are welcome.

If it helps, here are our parallactic angles for one of the cases that is failing: [177.029, 176.754, 176.475, 176.184, 175.77, 175.503, 175.222, 174.956, 174.535, 174.27, 173.992, 173.725, 173.314, 173.048, 172.778, 172.509, 172.091, 171.821, 171.551, 171.283, 157.135, 156.911, 156.682, 156.456, 156.112, 155.883, 155.665, 155.447, 155.1, 154.882, 154.659, 154.445, 154.11, 153.892, 153.68, 153.468, 153.144, 152.934, 152.727, 152.519]. We previously worried that a the large jump in parallactic angle could be causing the problem, but I used the sample data set supplied with the `VIP-extras` notebooks and removed a similar chunk in that data, and VIP was still successful.

Additionally, a minor issue that has made this all slightly more challenging: the notebooks in `VIP-extras` are out of sync with the latest version of VIP so there have been a few times where the functions that I need are only working in the latest version of VIP. This is not been a show-stopper, but I am curious if there will be new release of the notebooks that will be consistent with the latest VIP version soon. This does means that if there are functions in the latest released version that could help with the above problem, it's likely that I just haven't seen it yet so I apologize if that is that case and appreciate being pointed in the right direction.

Thanks!

(Tagging @juliengirard since we are working together on this project)

**Comment by oabsil** [comment]
Hi @kjbrooks 
Have you tried using the opposite sign for the parallactic angles? I know it's been a problem in the past. If it doesn't solve your problem, I would suggest to get in touch with @VChristiaens, who has a long experience processing NACO data with VIP.
Note that the VIP core developer (@carlgogo) is currently switching to a new job, so I'm not sure how much support he will be able to give in the coming weeks. Luckily, we will soon have a couple of new grad students to support the VIP development at ULiege, but it will take them a few months to get up to speed.

**Comment by kjbrooks** [comment]
Hi @oabsil,

Thank you! I will try this out soon. 

And thanks for the heads up on potential delays, I really appreciate it!

**Comment by VChristiaens** [comment]
Hi @kjbrooks,

Sorry for the slow reply - had an important deadline last week. If @oabsil 's suggestion did not work, you might want to try the attached script that is specific for NACO. It reads header values and return derotation angles required to align images to have North up and East left. I have not used it very recently so it's still in python 2, but it shouldn't be much work to make it compatible with python 3 if needed. 

Was the jump in parallactic angle due to a pause in the same observing sequence, or to the combination of datasets taken on separate nights? In the former case, there should not be any problem. In the latter case, you will have to divide the input file list in two - one for each dataset - and run the script separately for each. This is because the script uses pupil position angles and position angles on the detector which might be different for datasets obtained separately.

The returned values, when converted in a 1d array, can be provided directly to the VIP PCA- or median-ADI function. Hope this helps. 

Cheers,
Valentin

[derot_angles_naco.py.zip](https://github.com/vortex-exoplanet/VIP/files/3670666/derot_angles_naco.py.zip)

**Comment by kjbrooks** [comment]
Apologies for the delayed response. Like both of you, I have other deadlines that sometimes take precedence.

I was finally able to try your suggestions and found that switch the sign (as suggested by @oabsil ) was not successful, but using the `derot_angles_naco` script (as suggested by @VChristiaens) was. 

Unless either of you have anything else with regards to this issue, I think that it can probably be close. Thank you both for your help on this!
