### ISSUE TITLE
NEGFC firstguess how to add pixelscale

### ISSUE THREAD

**Issue by trisha-bhowmik** [vortex-exoplanet/VIP#557]
pixel = pixelscale
I was using initial_guess(cube_crop, rot, psf_norm, annulus_width=1, aperture_radius=1,ncomp=1,**plsc=pixel**, fmerit=mode,planets_xy_coord=source_xy, fwhm=fwhm,f_range=np.linspace(int(flx_min),int(flx_max),10))

 But now with firstguess(cube_crop, rot, psf_norm, annulus_width=1, aperture_radius=1,ncomp=1,**plsc=pixel**, fmerit=mode,planets_xy_coord=source_xy, fwhm=fwhm,f_range=np.linspace(int(flx_min),int(flx_max),10))

There is an error: **firstguess() got an unexpected keyword argument 'plsc'**

How do i add the pixelscale in the firstguess function?

**Comment by VChristiaens** [comment]
Hi @trisha-bhowmik, the `plsc` argument was removed in a recent version of VIP in order to reduce the number of parameters to the `firstguess` function, as I noticed it was effectively not used within the function. You should be able to safely run your code by just removing `plsc=pixel` from the call.
