### ISSUE TITLE
Array slicing in /var/shapes.get_square

### ISSUE THREAD

**Issue by astropatel** [vortex-exoplanet/VIP#72]
I ran into a a bug while running contrast_curve.

It seems that when the code encounters get_square under shapes.py online 140:

>array_view = array[y-wing:y+wing+1, x-wing:x+wing+1].copy()

A TypeError is called because y, x, and wing are not "ints". This seems to be ( atleast in the case of x and y) becuase when the centers are passed and calculated from shapes.frame_center, the centers are calculated using np.ceil, which returns "floats" and not "ints". I can temporarily put in fixes to the local copy I have. I've also attached the full traceback below. I hope I've correctly explained this. Let me know if additional information is required to address this.

![image](https://cloud.githubusercontent.com/assets/3648312/23820367/99a3e6c2-05cb-11e7-884a-86aadddfb4fe.png)
![image](https://cloud.githubusercontent.com/assets/3648312/23820372/b45abd88-05cb-11e7-9f30-825703f804a2.png)

**Comment by carlgogo** [comment]
Hi @astropatel thank you for reporting this bug. It happens with Numpy >= 1.12.0 (https://github.com/numpy/numpy/releases/tag/v1.12.0). Indexing with floats was changed from DeprecationWarning to IndexError. That's why you'll encounter this error only if you have updated Numpy recently. I'll fix this in VIP for its next release, which will be the version that goes with the paper (finally accepted).
