### ISSUE TITLE
classical ADI for nested_negfc_sampling

### ISSUE THREAD

**Issue by sbrems** [vortex-exoplanet/VIP#74]
Hello,
to get companion candidate's (CC) fluxes and positions, as far as I understood the MCMC_sampling got changed to a nested MCMC sampling. Meaning you call **vip.negfc.nested_negfc_sampling**.
But now I wonder if it is possible to do this approach **with classical ADI** (not PCA). I don't see a keyword or something to cange the algorithm. The reason why I do not want to use PCA/LLSG is that the CC is **in a corner where one cant create a full annulus**.
Thank you,
Stefan

PS: And a rather stupid question: how do you measure the **angles in this routine**? E.g. what is the angle of x,y = (2,1) wrt (0,0)? ±63° or ±27°? I just want to make sure I measure the right 'speckle' ;)

**Comment by carlgogo** [comment]
Hi @sbrems, sorry for my late reply. I took holidays and have been very busy since I came back. You probably figured these things out by now, but I'll try to answer your questions anyway:
1. the emcee based parameter estimation wasn't replaced. It's there. Now, there is an optional nested sampling based method,
2. I don't see why the NEGfc couldn't be used with classical ADI. There are a few things to change. Would you like to submit a pull request? I'd be glad to have a chat and help you contributing. 
3. the angles are measured from the positive X axis (3 pm) counter clockwise. 

I'll leave this issue open for the moment.

**Comment by sbrems** [comment]
Hy @carlgogo,

**Comment by sbrems** [comment]
Hey @carlgogo. thank you for the reply. The reason why I want to cADI is because the object is so close in a corner that it is not possible to get a full annulus where it is inside. Certainly one could pad it with zeros, but god knows how much the result is worth then. So I thought the easiest would be cADI ;)

**Comment by VChristiaens** [comment]
From v1.0.0 (and possibly earlier), it is possible to set a different algorithm than the default `pca_annulus` for all `negfc` routines. In particular, it can be set to `vip_hci.medsub.median_sub` (i.e. cADI).
